# First stage: build the JAR file
FROM maven:3.8.7-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

# Second stage: run the application
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/RentifyServer-1.1.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

